'use strict';
// Owner-approved launch content applied after the shared page-family composition.
const education={
 'kody-evans-bio':{training:['ADHD-CCSP','Level 1 Gottman Training']},
 'dr-nolan':{education:['Ph.D. in Clinical Sexology — Modern Sex Therapy Institutes, 2022','M.S. in Mental Health Counseling — The Johns Hopkins University, 2016'],training:['Clinical sexology focus','Gottman-informed therapy','Sex therapy-informed care']},
 'emily-johnsrud-bio':{education:['M.A. in Couples & Family Therapy — Seattle University, 2023'],training:['EMDR Trained','CBT training']},
 'gary-ashley':{education:['M.A. in Clinical Mental Health Counseling — Colorado Christian University, 2023','B.A. in Industrial Design — Metropolitan State University of Denver, 2002'],training:['Level 1 Gottman Training']},
 'new-page-47':{education:['Master of Social Work, Clinical Specialization — University of Washington, 2024'],training:['Acceptance & Commitment Therapy (ACT)','Cognitive Behavioral Therapy (CBT)','Dialectical Behavior Therapy (DBT) skills','Motivational Interviewing','Mindfulness, narrative, and somatic approaches']}
};
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function group(title,items){return items?.length?`<div class="mft-credential-group"><h3>${esc(title)}</h3><ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}
function insertBeforeFooterSections(html,block){
  for(const marker of ['<section class="section related reveal">','<section class="section final-cta reveal">','</main>']) if(html.includes(marker)) return html.replace(marker,block+marker);
  return html;
}
function clinician(html,slug){const x=education[slug];if(!x||html.includes('class="section mft-education"'))return html;const block=`<section class="section mft-education" aria-labelledby="education-training-title"><div class="section-heading"><p class="kicker">Background</p><h2 id="education-training-title">${x.education?'Education &amp; training':'Training'}</h2></div><div class="mft-credential-grid">${group('Education',x.education)}${group('Training',x.training)}</div></section>`;return insertBeforeFooterSections(html,block);}
function insurance(html){if(html.includes('class="section mft-insurance-detail"'))return html;const mail='mailto:support@mft.care?subject=Benefits%20verification&amp;body=Hello%20M.F.T.%2C%0A%0AI%20would%20like%20help%20checking%20therapy%20benefits.%0A%0AMy%20name%3A%20%0ABest%20phone%20number%3A%20%0AInsurance%20company%3A%20%0AClinician%20I%20am%20considering%20%28if%20known%29%3A%20%0AService%20I%20am%20seeking%3A%20%0AIn-person%20or%20telehealth%3A%20%0A%0APlease%20send%20me%20the%20secure%20next%20step%20for%20any%20member%20or%20plan%20details%20you%20need.%0A%0AThank%20you.';const block=`<section class="section mft-insurance-detail" aria-labelledby="insurance-detail-title"><div class="section-heading"><p class="kicker">Insurance support</p><h2 id="insurance-detail-title">Start with the plan, clinician, and service you intend to use.</h2><p>M.F.T. currently works with Premera, Aetna, Regence, and Cigna. Network participation and benefits can vary by clinician, service, and individual plan, so verification is required before relying on coverage.</p></div><div class="mft-info-grid"><article><h3>In-network plans</h3><p>Premera · Aetna · Regence · Cigna</p><p>Participation can vary by clinician and plan.</p></article><article><h3>Out-of-network</h3><p>Ask our support team whether a superbill is available for your service and what information your plan may require for reimbursement.</p></article><article><h3>Couples services</h3><p>Couples consultations and couples sessions are private pay. Do not assume an individual psychotherapy benefit applies to couples work.</p></article></div><div class="mft-email-panel"><h3>Request a benefits check</h3><p><a href="${mail}">Email support@mft.care to begin</a>. The email asks for your name, best phone number, carrier, clinician if known, service, and preferred format. Do not email insurance member numbers, dates of birth, diagnoses, or other sensitive clinical information. We will send the appropriate secure next step for anything else needed.</p></div></section>`;return insertBeforeFooterSections(html,block);}
function contact(html){if(html.includes('class="section mft-office-hours"'))return html;const block=`<section class="section mft-office-hours" aria-labelledby="office-hours-title"><div class="section-heading"><p class="kicker">Woodinville office</p><h2 id="office-hours-title">Office hours</h2></div><div class="mft-hours-grid"><p><strong>Monday</strong><span>9:00 AM – 7:00 PM</span></p><p><strong>Tuesday &amp; Wednesday</strong><span>8:00 AM – 7:00 PM</span></p><p><strong>Thursday &amp; Friday</strong><span>8:00 AM – 6:00 PM</span></p><p><strong>Saturday</strong><span>9:00 AM – 2:00 PM</span></p></div><p>19151 NE 144th Ave, Suite L, Woodinville, WA 98072 · (425) 659-0654 · <a href="mailto:support@mft.care">support@mft.care</a></p></section>`;return insertBeforeFooterSections(html,block);}
function home(html){if(html.includes('class="section mft-testimonials"'))return html;const block=`<section class="section mft-testimonials" aria-labelledby="client-feedback-title"><div class="section-heading"><p class="kicker">Client feedback</p><h2 id="client-feedback-title">What people have valued about the experience.</h2><p>These statements are paraphrased and anonymized from feedback previously published by M.F.T. Names and clinician identifiers are intentionally omitted. Individual experiences vary.</p></div><div class="mft-testimonial-grid"><blockquote><p>“We felt heard and found practical steps that helped us communicate more clearly and feel more connected.”</p></blockquote><blockquote><p>“The therapist felt approachable and relatable, which made a difficult process feel easier to begin.”</p></blockquote><blockquote><p>“The support felt practical and down-to-earth rather than distant or overly clinical.”</p></blockquote></div></section>`;return insertBeforeFooterSections(html,block);}
function apply(html,slug){if(education[slug])html=clinician(html,slug);if(slug==='check-my-coverage')html=insurance(html);if(slug==='therapy-contact-woodinville')html=contact(html);if(!slug)html=home(html);return html;}
const css=`\n.mft-credential-grid,.mft-info-grid,.mft-testimonial-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin-top:2rem}.mft-credential-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.mft-credential-group,.mft-info-grid article,.mft-testimonial-grid blockquote{margin:0;padding:1.5rem;background:var(--mist);border-top:3px solid var(--gold)}.mft-credential-group ul{padding-left:1.2rem;line-height:1.7}.mft-email-panel{margin-top:1.5rem;padding:1.5rem;border:1px solid var(--gold);background:#fff}.mft-hours-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem 2rem;max-width:850px}.mft-hours-grid p{display:flex;justify-content:space-between;gap:1rem;border-bottom:1px solid var(--line);padding:.8rem 0;margin:0}.mft-testimonial-grid blockquote p{font:500 1.2rem/1.6 var(--serif)}@media(max-width:760px){.mft-credential-grid,.mft-info-grid,.mft-testimonial-grid,.mft-hours-grid{grid-template-columns:1fr}}\n`;
module.exports={apply,css,education};
