'use strict';
// Public explanation of the owner's model. No assessment, scoring, enrollment or account API.
const ui=require('./ui/home-components');
const copy=require('../content/marriage-reset.json');
const {indexingEnabled}=require('./seo-safety');
const crypto=require('node:crypto');
const BOOK=require('../content/simplepractice-booking.json').generalUrl;
const LOGIN='https://ops.mft.care/';
const routes=['marriagereset','marriage-reset-assessment','marriage-reset-assessment/thanks'];
const revision=crypto.createHash('sha256').update(JSON.stringify(copy)).digest('hex');
const p=(key,...indices)=>indices.map(i=>copy.blocks[key].paragraphs[i]);
const at=(key,i)=>p(key,i)[0];
const join=(key,...indices)=>p(key,...indices).join(' ');
const source=(html,keys)=>html.replace('<section ',`<section data-mr-source="${keys.join(' ')}" `);
const steps=copy.blocks.cycle.paragraphs.slice(2,7).map((s,i)=>{const [name,description]=s.split('\n');return {name,description,id:['understand','prioritize','practice','measure','adapt'][i]};});
function enabled(env=process.env){return env.CONTEXT!=='production'&&!indexingEnabled(env);}
function validate(){
 if(copy.version!==1||copy.publication!=='review-only'||!/^[a-f0-9]{64}$/.test(copy.source.sha256))throw Error('Invalid Marriage.Reset source');
 for(const k of ['overview','assessment','adaptive','understand','decision','sequence','continuity','practice','participation','reassessment','evolve','privacy','safety','uncertainty','limitations','human','history','entry','cycle','faq','closing']){
  const b=copy.blocks[k];if(!b||!Number.isInteger(b.sourceStartLine)||!b.paragraphs.every(s=>typeof s==='string'&&s.trim()))throw Error('Missing Marriage.Reset source block: '+k);
 }
 if(steps.map(x=>x.name).join('|')!=='Understand|Prioritize|Practice|Measure|Adapt')throw Error('Invalid source journey');
 if(copy.blocks.faq.paragraphs.length!==16)throw Error('Expected eight source FAQs');
 return true;
}
function access(){return `<div class="mr-member-access"><p>Already enrolled through your care team?</p><a class="button ghost" data-ui="button" data-mr-client-access href="${LOGIN}" rel="noopener noreferrer">Marriage.Reset client sign-in <span aria-hidden="true">&rarr;</span></a></div>`;}
function hero(assessment=false){return source(ui.hero({kicker:'Marriage.Reset\u2122 | Marriage.Family.Therapy',title:assessment?'Your first assessment. Your own perspective.':'Couples therapy with a clearer sense of direction.',summary:assessment?'A progressive beginning: enough information to help your therapist make the next useful clinical decision, with room for each partner to answer privately.':at('overview',0),actions:[{label:assessment?'How the assessment works':'Explore the relationship journey',href:assessment?'#understand':'#the-journey'},{label:'Schedule a consultation',href:BOOK}],panel:{kicker:'A clinician-guided model',title:'Structure for the work. Not a substitute for your therapist.',paragraphs:p('decision',0,1),items:[{title:'New to Marriage.Reset?',text:'Begin through care with the M.F.T. team.',href:'#begin'},{title:assessment?'Explore the whole model':'Understand the assessment',text:assessment?'See how assessment connects with practice and progress.':'Learn why each partner has a separate starting experience.',href:assessment?'/marriagereset/':'/marriage-reset-assessment/'}]}}),['overview','decision'])+access();}
function cycle(){return `<section class="section mft-component mr-cycle" id="the-journey" aria-labelledby="the-journey-title" data-ui="journey" data-mr-source="cycle"><div class="section-heading"><p class="kicker">A continuing relationship journey</p><h2 id="the-journey-title">Understand. Prioritize. Practice. Measure. Adapt.</h2><p>${ui.esc(at('overview',9))}</p></div><nav aria-label="Explore the five parts of Marriage.Reset"><ol class="mr-cycle-grid">${steps.map((s,i)=>`<li><a href="#${s.id}" data-ui="card"><span class="mr-stage-number" aria-hidden="true">0${i+1}</span><h3>${s.name}</h3><p>${ui.esc(s.description)}</p><span class="mr-cycle-action">Explore this part <span aria-hidden="true">&rarr;</span></span></a></li>`).join('')}</ol></nav><p class="mr-cycle-return">${ui.esc(at('cycle',7))} <span aria-hidden="true">&larr;</span></p></section>`;}
function overview(){return source(ui.story({id:'the-model',kicker:'The question beneath the question',title:'Relationships are complicated. The first step does not have to explain everything.',paragraphs:[...p('overview',1,2,4),at('overview',6)],panel:{kicker:'What the model helps you ask',title:'Where do we begin?',items:at('overview',8).split('\n').map((title,i)=>({title,text:steps[[0,1,1,3][i]].description,href:'#'+steps[[0,1,1,3][i]].id}))}}),['overview']);}
function assessmentSection(){return source(ui.story({id:'understand',kicker:'01 | Understand',title:'Progressive rather than exhaustive.',paragraphs:[join('assessment',1,2,3),...p('assessment',4,5,6),`[Explore the assessment in more detail.](/marriage-reset-assessment/#why-it-changes)`],panel:{kicker:'A focused beginning',title:'Learn what we need to learn next.',paragraphs:p('assessment',7,8),items:[{title:'Approximately 30\u201332 questions',text:'The typical initial assessment target.',href:'/marriage-reset-assessment/#why-it-changes'},{title:'49 questions in ordinary circumstances',text:'Clinically necessary safety follow-up may extend beyond the ordinary limit.',href:'#privacy-and-safety'}]}}),['assessment']);}
function adaptive(){return source(ui.disclosures({id:'why-it-changes',kicker:'A common foundation. Different follow-up.',title:'The assessment follows what needs to be understood.',intro:join('adaptive',0,5,6,7),tone:'mft-solid-cards',columns:3,items:[{title:'Different starting points',teaser:'Two couples can bring very different needs into care.',paragraphs:[join('adaptive',1,2),join('adaptive',3,4)]},{title:'Questions with a purpose',teaser:at('understand',0),paragraphs:[join('understand',2,3),join('understand',4,5),join('understand',6,7),at('understand',8)]},{title:'Unknown is not the same as fine',teaser:at('adaptive',10),paragraphs:[at('adaptive',8),join('uncertainty',2,3,4,5)]}]}),['adaptive','understand','uncertainty']);}
function prioritize(){return source(ui.steps({id:'prioritize',kicker:'02 | Prioritize',title:'What needs to happen first?',intro:join('sequence',0,1),items:[{title:'Safety and readiness first',paragraphs:[at('sequence',3),at('safety',5)]},{title:'Active relationship injuries',paragraphs:[at('sequence',2)]},{title:'Important bottlenecks',paragraphs:[at('sequence',4)]},{title:'Areas for meaningful leverage',paragraphs:[at('understand',6),at('sequence',7)]}],note:'This is the model\u2019s general clinical logic, not an automated decision about your relationship.'}),['sequence','understand','safety']);}
function directions(){return source(ui.comparison({id:'treatment-direction',kicker:'Enough information, not artificial certainty',title:'Up to three useful directions. Not three just to fill a list.',items:[{title:'When the evidence supports a direction',paragraphs:[at('decision',2),join('decision',3,4),at('decision',1)]},{title:'When more needs to be understood',paragraphs:p('decision',5,6,0)}]}),['decision']);}
function practice(){return source(ui.story({id:'practice',kicker:'03 | Practice',title:'The work continues between appointments.',paragraphs:[join('practice',0,1),join('practice',2,3),at('practice',5)],panel:{kicker:'Connected to the clinical work',title:'Modules support therapy. They do not replace it.',paragraphs:[at('practice',4),join('continuity',0,1),join('continuity',2,3),at('continuity',5)]}}),['practice','continuity']);}
function measure(){return source(ui.comparison({id:'measure',tone:'mr-feature',kicker:'04 | Measure',title:at('participation',1),intro:at('participation',5),items:[{title:'Participation',paragraphs:[...p('participation',2,3,4),at('participation',6)]},{title:'Evidence of change',paragraphs:[join('reassessment',0,1),join('reassessment',2,3)],}],note:'The better question is: '+at('reassessment',7)}),['participation','reassessment']);}
function adapt(){return source(ui.story({id:'adapt',kicker:'05 | Adapt',title:'Your first assessment is not a permanent description of your relationship.',paragraphs:[join('evolve',0,1,2,3),join('evolve',4,5,6),join('evolve',7,8)],panel:{kicker:'A timeline, not disconnected snapshots',title:'Keep learning without losing the history.',paragraphs:[at('history',0),at('history',1),at('history',2),at('history',3)]}}),['evolve','history']);}
function privacy(){return source(ui.disclosures({id:'privacy-and-safety',kicker:'Two private voices. One relationship.',title:'Understanding each other is not a competition.',intro:at('privacy',0)+' '+at('privacy',3),tone:'mft-solid-cards',columns:3,items:[{title:'Each partner has a private voice',teaser:at('privacy',1),paragraphs:p('privacy',2,4,5)},{title:'Safety is different',teaser:at('safety',5),paragraphs:[join('safety',0,1,2),at('safety',3)]},{title:'We may not know yet',teaser:at('adaptive',10),paragraphs:[join('uncertainty',1,2,3),join('uncertainty',4,5)]}]}),['privacy','safety','uncertainty']);}
function boundaries(){return source(ui.comparison({id:'human-care',kicker:'Human care remains at the center',title:'A clinical framework. Not an automatic therapist.',items:[{title:'Your clinician remains responsible',paragraphs:[join('human',0,1),at('human',2),join('human',3,4)]},{title:'M.F.T.-authored measures',paragraphs:p('limitations',0,1,2,3)}]}),['human','limitations']);}
function questions(){const a=copy.blocks.faq.paragraphs;return source(ui.faq({id:'questions',kicker:'Frequently asked questions',title:'Clarity before you begin.',items:Array.from({length:8},(_,i)=>({question:a[i*2],answer:a[i*2+1]}))}),['faq']);}
function enrollment(){return `<section class="section mft-component mr-entry" id="begin" aria-labelledby="begin-title" data-ui="entry" data-mr-source="entry closing">${ui.heading({id:'begin',kicker:'Begin with Marriage.Family.Therapy',title:at('closing',0),intro:at('closing',1)})}<div class="mr-entry-grid"><div>${ui.paragraphs([at('entry',0),at('entry',2),at('closing',3)])}<div class="actions">${ui.button({label:'Schedule a consultation',href:BOOK})}${ui.button({label:'Explore couples care',href:'/marriage-and-couples-therapy-counseling/'},'ghost')}</div><p class="mr-entry-note">${ui.esc(at('entry',1))}</p></div><aside class="home-hero-panel" data-ui="panel"><p class="kicker">Already invited?</p><h2>Return to your Marriage.Reset space.</h2>${ui.paragraphs([at('entry',3)])}<a class="button light" data-ui="button" data-mr-client-access href="${LOGIN}" rel="noopener noreferrer">Marriage.Reset client sign-in <span aria-hidden="true">&rarr;</span></a></aside></div></section>`;}
function assessmentMain(){return hero(true)+ui.jump([{id:'understand',label:'Your assessment'},{id:'why-it-changes',label:'Progressive questions'},{id:'privacy-and-safety',label:'Privacy and safety'},{id:'treatment-direction',label:'What follows'},{id:'questions',label:'Questions'},{id:'begin',label:'Getting started'}])+assessmentSection()+adaptive()+privacy()+directions()+source(ui.cards({id:'the-next-step',kicker:'The beginning of care, not the end',title:'Your assessment connects to a continuing journey.',columns:3,items:[{title:'Prioritize',text:at('cycle',3).split('\n')[1],href:'/marriagereset/#prioritize',action:'Explore treatment priorities'},{title:'Practice',text:at('cycle',4).split('\n')[1],href:'/marriagereset/#practice',action:'Explore between-session work'},{title:'Measure and adapt',text:at('cycle',5).split('\n')[1]+' '+at('cycle',6).split('\n')[1],href:'/marriagereset/#measure',action:'Explore evidence of change'}]}),['cycle'])+questions()+enrollment();}
function fallback(slug){return ui.hero({kicker:'Marriage.Reset | Care-team invitations',title:slug.endsWith('/thanks')?'Continue through your care team.':'Marriage.Reset begins through your care team.',summary:at('entry',2),actions:[{label:'Learn about Marriage.Reset',href:'/marriagereset/'},{label:'Schedule a consultation',href:BOOK}],panel:{title:'An invitation, not public self-enrollment.',paragraphs:[at('entry',1),at('entry',3)]}})+access();}
function render(slug,rich=enabled()){
 validate();if(!routes.includes(slug))throw Error('Unknown Marriage.Reset route');
 const body=!rich||slug.endsWith('/thanks')?fallback(slug):slug==='marriagereset'?hero()+overview()+cycle()+assessmentSection()+adaptive()+prioritize()+directions()+practice()+measure()+adapt()+privacy()+boundaries()+questions()+enrollment():assessmentMain();
 return `<main id="main" data-marriage-reset="${rich?'review':'invitation-only'}" data-mr-revision="${revision}" data-design-system="homepage-shared-v1">${body}<aside class="mft-care-note mft-component">This page explains the Marriage.Reset model developed by Marriage.Family.Therapy. It is not an assessment and does not collect partner answers.</aside></main>`;
}
function metadata(html,slug){
 const title=slug==='marriagereset'?'Marriage.Reset | A Clinician-Guided Relationship Journey':slug.endsWith('/thanks')?'Marriage.Reset | Continue Through Your Care Team':'Marriage.Reset Assessment | A Progressive Beginning';
 const desc=slug==='marriagereset'?'Understand, prioritize, practice, measure, and adapt. Explore the Marriage.Reset relationship-care model and how couples begin through Marriage.Family.Therapy.':slug.endsWith('/thanks')?'Marriage.Reset begins through your care team. Learn about individual partner invitations and returning to an established account.':'Learn how Marriage.Reset uses progressive assessment, private partner perspectives, and clinical judgment to identify the next useful step in relationship care.';
 let out=html.replace(/<title>.*?<\/title>/,`<title>${title}</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${desc}">`).replace(/<meta property="og:title" content="[^"]*">/,`<meta property="og:title" content="${title}">`).replace(/<meta property="og:description" content="[^"]*">/,`<meta property="og:description" content="${desc}">`);
 return out.replace(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/,(_,raw)=>{const schema=JSON.parse(raw);for(const n of schema['@graph']||[])if(n['@type']==='WebPage'){n.name=title;n.description=desc;delete n.reviewedBy;delete n.lastReviewed;}return '<script type="application/ld+json">'+JSON.stringify(schema).replace(/</g,'\\u003c')+'</script>';});
}
function prepare(html,slug){
 // Retire obsolete public access collection in ALL build modes before form discovery.
 // Rich model pages remain review-only; production rehearsal receives only the entry boundary.
 let out=html.replace(/>Verify insurance<\/a>/g,'>Verify benefits</a>').replace(/(<a\b[^>]*href="\/marriage-reset-assessment\/(?:#[^"]*)?"[^>]*>)([\s\S]*?)(<\/a>)/g,(_,open,body,close)=>open+body.replace(/Start the free Marriage\.Reset assessment|Start the free assessment|Request free access|Try Marriage\.Reset/g,'Understand the Marriage.Reset assessment')+close);
 out=out.replace(/Begin with the free relationship assessment and discover what deserves attention\./g,'Explore the progressive assessment and care-team invitation process.');
 if(routes.includes(slug)){
  if(!/<main\b[^>]*>[\s\S]*?<\/main>/.test(out))throw Error('Missing Marriage.Reset shell');
  out=out.replace(/<main\b[^>]*>[\s\S]*?<\/main>/,render(slug,false));out=metadata(out,slug);
  out=out.replace(/<header class="site-header">[\s\S]*?<\/header>/,h=>h.replace(/>Free consultation<\/a>/g,'>Consultation</a>'));
 }
 return out;
}
module.exports={copy,routes,revision,steps,enabled,validate,render,metadata,prepare,has:s=>routes.includes(s)};
